name: DAST LAB Env

on:
  pull_request:
    branches:
      - master
      -  main
  workflow_dispatch:
  
jobs:
  dast:
    runs-on: ubuntu-latest
    name: DAST on Prem Testing Action
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create Output folder
        run: mkdir ${{ github.workspace }}/output_fold
      - name: Change dir owner
        run: sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.6
        env:
          CX_APIKEY: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhODZiNjEzNC0xZGMwLTRjMjktODIyYi0zZDhhYmRjYzg1NTYifQ.eyJpYXQiOjE3MTMyNDE1OTgsImp0aSI6ImYzNWU0NmNhLTdmOWEtNGI0YS05NGY0LTBmNjI2ODcxYTA3MyIsImlzcyI6Imh0dHBzOi8vZGV1LmlhbS5jaGVja21hcngubmV0L2F1dGgvcmVhbG1zL2NoZWNrbWFyeC1nbG9iYWwtc2VydmljZXMtaW50ZXJuYWwiLCJhdWQiOiJodHRwczovL2RldS5pYW0uY2hlY2ttYXJ4Lm5ldC9hdXRoL3JlYWxtcy9jaGVja21hcngtZ2xvYmFsLXNlcnZpY2VzLWludGVybmFsIiwic3ViIjoiYWY1ZTA0YWMtMTMyYi00MzY5LTg4OWYtN2EyNTEyOWViMzM3IiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImFzdC1hcHAiLCJzZXNzaW9uX3N0YXRlIjoiOTg4ZDYxM2ItMzA2Yy00NzhkLTlkNWEtYmVhYWU3Y2U2ODI4Iiwic2NvcGUiOiIgb2ZmbGluZV9hY2Nlc3MiLCJzaWQiOiI5ODhkNjEzYi0zMDZjLTQ3OGQtOWQ1YS1iZWFhZTdjZTY4MjgifQ.oPhGEazFtPh9_AkrPDrBdzH_h1kltSft__zToXdytdY
        with:
          command: web
          config: dast-config/zap_config.yaml
          environment_id: 840df6a6-ef07-4aec-b84a-5359fdef299d
          fail_on: "HIGH"
          log_level: info
          base_url: https://deu.ast.checkmarx.net/
          verbose: true
          timeout: 100000
          output: ${{ github.workspace }}/output_fold
      - name: Change dir owner back to gh user
        if: always()
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_fold  
      - uses: actions/upload-artifact@v3
        if: always()
        name: Upload Logs
        with:
          name: report
          path: ${{ github.workspace }}/output_fold
